name: Despliegue Terraform con LocalStack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Esperar a que LocalStack esté listo
      run: |
        until curl -s http://localhost:4566/_localstack/health | grep '"s3": "running"'; do
          echo "Esperando LocalStack..."
          sleep 5
        done

    - name: Inicializar Terraform
      run: terraform init

    - name: Plan de Terraform
      run: terraform plan

    - name: Aplicar Terraform
      run: terraform apply -auto-approve
